/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author Igor
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        la_usuario = new javax.swing.JLabel();
        la_senha = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        jb_entrar = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mb_barrademenu = new javax.swing.JMenuBar();
        jm_conexao = new javax.swing.JMenu();
        mi_configConexao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(566, 371));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        la_usuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        la_usuario.setForeground(new java.awt.Color(255, 255, 255));
        la_usuario.setText("Usuário:");
        getContentPane().add(la_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, 30));

        la_senha.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        la_senha.setForeground(new java.awt.Color(255, 255, 255));
        la_senha.setText("Senha:");
        getContentPane().add(la_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 100, 30));

        tf_user.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 170, 30));
        getContentPane().add(pf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 30));

        jb_entrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jb_entrar.setText("Entrar");
        getContentPane().add(jb_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 90, -1));

        jb_sair.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jb_sair.setText("Sair");
        getContentPane().add(jb_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/BGLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 660, 410));

        jm_conexao.setText("Conexão");

        mi_configConexao.setText("Configurar conexão...");
        jm_conexao.add(mi_configConexao);

        mb_barrademenu.add(jm_conexao);

        setJMenuBar(mb_barrademenu);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-613)/2, (screenSize.height-421)/2, 613, 421);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_sair;
    private javax.swing.JMenu jm_conexao;
    private javax.swing.JLabel la_senha;
    private javax.swing.JLabel la_usuario;
    private javax.swing.JMenuBar mb_barrademenu;
    private javax.swing.JMenuItem mi_configConexao;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
